### ISSUE TITLE
Cannot find on haxelib

### ISSUE THREAD

**Issue by tong** [proletariatgames/hxnodejs-ws#1]
The library does not show up on a search on haxelib.
https://lib.haxe.org/search/?v=websocket

First i thought because there is no 'websocket' tag in haxelib.json ( only 'websockets') but  neither:
https://lib.haxe.org/search/?v=websockets

… which makes it a haxelib issue (HaxeFoundation/haxelib#169), but any idea ?

**Comment by waneck** [comment]
That is weird. I have just made a new haxelib release (non-alpha) but it still won't show up. I'm going to close this as this is most probably a haxelib issue
